# Generated by Django 4.0.6 on 2022-11-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_topping_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topping',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
