# Generated by Django 4.0.6 on 2022-11-24 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_topping_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='pizza_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
