# Generated by Django 4.0.6 on 2022-11-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping_list',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='pizza',
            unique_together={('pizza_owner', 'pizza_name', 'topping_list')},
        ),
    ]
