# Generated by Django 4.0.6 on 2022-11-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_pizza_pizza_name_alter_pizza_topping_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='topping_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='topping',
            unique_together={('pizza_owner', 'topping_name')},
        ),
    ]
