# Generated by Django 4.1.3 on 2022-11-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_topping_topping_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pizza',
            unique_together={('pizza_owner', 'pizza_name'), ('pizza_name', 'topping_list')},
        ),
    ]
