# Generated by Django 4.1.3 on 2022-11-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pizza_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pizza',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pizza',
            constraint=models.UniqueConstraint(fields=('pizza_owner', 'pizza_name'), name='unique_pizza_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='pizza',
            constraint=models.UniqueConstraint(fields=('pizza_owner', 'topping_list'), name='unique_pizza_owner_topping'),
        ),
    ]
